name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
  
      - name: Install node_modules
        run: npm install 

      - name: Start server
        run: node server.js &
        working-directory: server

      - name: Start application
        run: npm run start &

      - name: Install playwright
        run: npx playwright install

      - name: Run tests
        run: npx playwright test ui.test.js &
        working-directory: tests

  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Use Node.js 18.x
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18.x
  #         cache: "npm"

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Start server
  #       run: node server.js &        
  #       working-directory: server

  #     - name: Start application
  #       run: npm run start &

  #     - name: Install playwright
  #       run: npx playwright install

  #     - name: Run tests
  #       run: npx playwright test ui.test.js &
  #       working-directory: tests
  deploy:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.API_TOKEN }}
    